import type { Metadata } from "next";
import "./globals.css";
import TopNav from "../components/navBar/TopNav";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Providers from "../components/Providers";
import { getAuthUserIdFromSession } from "../actions/authActions";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userId = await getAuthUserIdFromSession();

  return (
    <html lang="en">
      <body>
        <Providers userId={userId}>
          <ToastContainer
            position="bottom-right"
            hideProgressBar
            className="z-50"
          />
          <TopNav />
          <main className="container mx-auto"> {children}</main>
        </Providers>
      </body>
    </html>
  );
}
